export default {
  PROJECT_ID_MAINNET: 'DUMMY_MAINNET',
  PROJECT_ID_TESTNET: 'DUMMY_TESTNET',
  PROJECT_ID_PREVIEW: 'DUMMY_PREVIEW',
  PROJECT_ID_PREPROD: 'DUMMY_PREPROD',
  POSTHOG_API_KEY: 'DUMMY_POSTHOG_API_KEY',
  POSTHOG_PROJECT_ID: 'DUMMY_POSTHOG_PROJECT_ID',
};
